name: Build Custom RustDesk Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Configure custom server
      shell: pwsh
      run: |
        # 修改配置文件
        $configFile = "libs\hbb_common\src\config.rs"
        $content = Get-Content $configFile -Raw
        
        # 替换服务器地址
        $content = $content -replace 'rs-ny\.rustdesk\.com', '47.100.22.91'
        $content = $content -replace 'rs-sg\.rustdesk\.com', '47.100.22.91'
        
        # 在 get_key 函数添加默认key
        if ($content -match '(pub fn get_key\(\) -> String \{[^}]+\})') {
            $oldFunc = $matches[1]
            $newFunc = $oldFunc -replace '(Config::get_option\("key"\))', '$1;`n            if key.is_empty() {`n                key = "ejHEEuKd761NA6Q82WMsnNBaKxYhXhMFs1qdUzrJEPY=".to_string();`n            }'
            $content = $content -replace [regex]::Escape($oldFunc), $newFunc
        }
        
        Set-Content -Path $configFile -Value $content
        
    - name: Build RustDesk
      run: python build.py --portable
        
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: RustDesk-Windows-Custom
        path: |
          rustdesk-*.exe
          target/release/rustdesk-portable-packer.exe